LANGUAGE = "en"

if(LANGUAGE == "en") then
	SPLAY = "Play"
	SOPTIONS = "Options"
	SSTORE = "Store"
	SLEADERBOARD = "Leaderboards"
	SACHIEVEMENTS = "Achievements"
	S2TRACKS = "2 Pistas"
	S3TRACKS = "3 Pistas"
	S4TRACKS = "4 Pistas"
	SEASY = "Facil"
	SNORMAL = "Normal"
	SHARD = "Dificil"
	SINSANE = "Insano"
elseif(LANGUAGE == "pt") then
	SPLAY = "Jogar"
	SOPTIONS = "Opcoes"
	SSTORE = "Loja"
	SLEADERBOARD = "Classificacao"
	SACHIEVEMENTS = "Conquistas"
	S2TRACKS = "2 Pistas"
	S3TRACKS = "3 Pistas"
	S4TRACKS = "4 Pistas"
	SEASY = "Easy"
	SNORMAL = "Normal"
	SHARD = "Hard"
	SINSANE = "Insane"
end
